version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: local_mysql_db
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_paper
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
# DATABASE_URL=mysql://root:root@localhost:33061/e_paper
