name: Sync Fork with Upstream

on:
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIV_TOKEN }}
          
      - name: Configure Git Identity
        run: |
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/zzVu77/e-paper.git
          git fetch upstream

      - name: Sync Main Branch
        run: |
          set -e
          git checkout main || git checkout -b main
          git merge upstream/main --allow-unrelated-histories
          git push origin main

      - name: Sync Develop Branch
        run: |
          set -e
          git checkout develop || git checkout -b develop
          git merge upstream/develop --allow-unrelated-histories
          git push origin develop
