name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v3

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/zzVu77/e-paper.git
          git fetch upstream

      - name: Sync Main Branch
        run: |
          git checkout main
          git merge upstream/main
          git push origin main

      - name: Sync Develop Branch
        run: |
          git checkout develop
          git merge upstream/develop
          git push origin develop
